### ISSUE TITLE
Use app server managed resources instead

### ISSUE THREAD

**Issue by AlphaBeth** [LeTrongDat/WebProgramming#2]
https://github.com/LeTrongDat/WebProgramming/blob/c301060bae7d65003aa1c865ed9c107c29c4a42e/src/main/resources/META-INF/persistence.xml#L14-L15

See "wildfly jdbc connection pool" and how to use it in JPA.

**Comment by LeTrongDat** [comment]
8778c815e2bc75113d4f7a9c010d5ba564921295
